# Generated by Django 5.2.1 on 2025-05-30 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('sku', models.CharField(db_index=True, max_length=100, unique=True)),
                ('price', models.DecimalField(db_index=True, decimal_places=2, max_digits=10)),
                ('inventory_quantity', models.IntegerField(db_index=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
