# Generated by Django 5.2.1 on 2025-05-26 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_id_alter_product_inventory_quantity_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
